language: android
# jdk: oraclejdk7

android:
  components:
  - platform-tool
      - tool
      - android-22
      - build-tools-22.0.1
      - extra-android-m2repository
      - extra-google-m2repository
